name: oxford_dict
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/rIIh

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  chopper: ^3.0.3
  json_annotation: ^3.1.0

dev_dependencies:
  effective_dart: ^1.2.4
  build_runner: ^1.10.1
  json_serializable: ^3.5.0
  chopper_generator: ^3.0.5
  test: ^1.15.4
